version: "3.9"

services:
  redis:
    image: redis:alpine
    container_name: ledgify_redis
    ports:
      - "6379:6379"
    networks:
      - ledgify_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:15-alpine
    container_name: ledgify_postgres
    environment:
      POSTGRES_DB: ledgify_db
      POSTGRES_USER: ledgify_admin
      POSTGRES_PASSWORD: ledgify
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ledgify_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ledgify_admin -d ledgify_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:6
    container_name: ledgify_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ledgify_doc_admin
      MONGO_INITDB_ROOT_PASSWORD: ledgify
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - ledgify_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  mongodata:

networks:
  ledgify_net:
    driver: bridge